apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
spec:
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
      - name: socket
        image: getliberated/yantoo-socket
        env:
          - name: CHAT_URL
            value: https://chat-service-url
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
