apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: getliberated/yantoo-user
        env:
          - name: ATLAS_URI
            value: mongodb+srv://user:pass@cluster0-qidwa.gcp.mongodb.net/final-project?retryWrites=true&w=majority
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
        ports:
        - containerPort: 3000
